package de.unidue.inf.is.utils;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

import com.ibm.db2.jcc.DB2Driver;



public final class DBUtil {

    private DBUtil() {
    }

    //static because only one such driver can be created. No copies should exist!
    static {
        com.ibm.db2.jcc.DB2Driver driver = new DB2Driver();
        try {
            DriverManager.registerDriver(driver);
        }
        catch (SQLException e) {
        	//custom error added along with the error generated by SQLException
            throw new Error("Error in loading Database Driver!");
        }
    }
   
   // This method is used to connect to Uni Server
    public static Connection getExternalConnection() throws SQLException {
        Properties properties = new Properties();
        
        InputStream input = null;
    	try {
    		input = new FileInputStream("settings.properties");
    		properties.load(input);
    	} catch (IOException ex) {
    		ex.printStackTrace();
    	}
    	
		String user = properties.getProperty("gruppenname");
		String pass = properties.getProperty("passwort");
		String rechnername = properties.getProperty("rechnername");
		String database = properties.getProperty("database");
		//split is not necessary
		String gruppennummer = user.split("(?<=\\D)(?=\\d)")[1];

        final String url = "jdbc:db2://"+rechnername+".is.inf.uni-due.de:50"+gruppennummer+"/" + database + ":currentSchema="+user+";";
        Connection connection = DriverManager.getConnection(url, user,pass);
        return connection;
    }


    public static boolean checkDatabaseExistsExternal() {
        boolean exists = false;

        try (Connection connection = getExternalConnection()) {
            exists = true;
        }
        catch (SQLException e) {
            exists = false;
            e.printStackTrace();
        }

        return exists;
    }


 

}